server:
  port: 8080

spring:
  application:
    name: flame

management:
  endpoint:
    info:
      enabled: true
      git:
        mode: full
    shutdown:
      enabled: false
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
      livelinessState:
        enabled: true
      readinessState:
        enabled: true
    loggers:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - info
          - health
          - prometheus
          - loggers
          - httptrace

info:
  app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
  git:
    branch: ${git.branch}
    commit:
      id: ${git.commit.id}
      time: ${git.commit.time}