name: Docker Image CI

on:
  workflow_run:
    workfows: [DISABLED]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spark-flame:1.1.0
