
name: Secrets

on:
  push:
    branches: [ "feature/secret-leak"]

jobs:
  build:

    runs-on: spark-runner-scaleset-1

    steps:
    - name: Install xxd
      run: sudo apt-get install -y xxd
    - name: leak
      env:
        topsecret: ${{ secrets.TOPSECRET }}
      run: |
          echo "topsecret: ${topsecret}"
          echo "secrets.TOPSECRET: ${{secrets.TOPSECRET}}"
          echo "Trying xxd..."
          echo ${topsecret} | xxd -p
          echo "Trying base64..."
          echo ${topsecret} | base64
          echo "DONE"
