
name: Secrets


on:
  push:
    branches: [ "feature/secret-leak"]

jobs:
  build:

    runs-on: spark-runner-scaleset-1

    steps:
    - name: leak
      env:
        topsecret: ${{ secrets.TOPSECRET }}
      run: |
          echo "topsecret: ${topsecret}"
          echo "secrets.TOPSECRET: ${{secrets.TOPSECRET}}"
          echo "Trying base64..."
          echo "${topsecret}" | base64
          echo "Trying base64 x2 ..."
          echo "${topsecret}" | base64 | base64 --decode
          echo "DONE"
